"""create initial Land CRM schema

Revision ID: c5b3143bbb38
Revises: 
Create Date: 2026-10-01 20:01:44.953371
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c5b3143bbb38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('return_to', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('oidc_issuer', sa.String(length=500), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_issuer', 'oidc_subject', name='uq_user_oidc_identity')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('land_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_kind'), 'background_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_background_jobs_tenant_id'), 'background_jobs', ['tenant_id'], unique=False)
    op.create_table('device_push_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_push_token')
    )
    op.create_index(op.f('ix_device_push_tokens_user_id'), 'device_push_tokens', ['user_id'], unique=False)
    op.create_table('document_classes',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('default_access_policy', sa.String(length=20), nullable=False),
    sa.Column('requires_expiry', sa.Boolean(), nullable=False),
    sa.Column('applies_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_document_class_key')
    )
    op.create_index(op.f('ix_document_classes_tenant_id'), 'document_classes', ['tenant_id'], unique=False)
    op.create_table('geo_units',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('local_name', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geo_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'parent_id', 'level', 'name', name='uq_geo_unit')
    )
    op.create_index(op.f('ix_geo_units_level'), 'geo_units', ['level'], unique=False)
    op.create_index(op.f('ix_geo_units_parent_id'), 'geo_units', ['parent_id'], unique=False)
    op.create_index(op.f('ix_geo_units_tenant_id'), 'geo_units', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('owners',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('local_name', sa.String(length=300), nullable=True),
    sa.Column('relation_name', sa.String(length=300), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('readiness', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_code'), 'owners', ['code'], unique=False)
    op.create_index(op.f('ix_owners_full_name'), 'owners', ['full_name'], unique=False)
    op.create_index(op.f('ix_owners_tenant_id'), 'owners', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_owners_verification_status'), 'owners', ['verification_status'], unique=False)
    op.create_table('roles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_role_tenant_key')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('scoring_models',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_models_tenant_id'), 'scoring_models', ['tenant_id'], unique=False)
    op.create_table('tenant_invitations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_invitation_email')
    )
    op.create_index(op.f('ix_tenant_invitations_tenant_id'), 'tenant_invitations', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_membership')
    )
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False)
    op.create_table('tenant_sequences',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'name')
    )
    op.create_table('tenant_template_permissions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'template_id')
    )
    op.create_table('web_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_hash', sa.String(length=128), nullable=False),
    sa.Column('encrypted_tokens', sa.Text(), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_time', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_hash')
    )
    op.create_index(op.f('ix_web_sessions_user_id'), 'web_sessions', ['user_id'], unique=False)
    op.create_table('workflow_template_versions',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )
    op.create_index(op.f('ix_workflow_template_versions_template_id'), 'workflow_template_versions', ['template_id'], unique=False)
    op.create_table('membership_roles',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['tenant_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id')
    )
    op.create_table('owner_contacts',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_contacts_owner_id'), 'owner_contacts', ['owner_id'], unique=False)
    op.create_table('properties',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('land_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('state_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('tehsil_id', sa.Uuid(), nullable=True),
    sa.Column('village_id', sa.Uuid(), nullable=True),
    sa.Column('survey_number', sa.String(length=100), nullable=True),
    sa.Column('khasra_number', sa.String(length=100), nullable=True),
    sa.Column('khata_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('active_geometry_id', sa.Uuid(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('area_unit', sa.String(length=20), nullable=True),
    sa.Column('area_sqm_derived', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('land_use', sa.String(length=60), nullable=True),
    sa.Column('road_access', sa.String(length=20), nullable=False),
    sa.Column('road_frontage_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('road_frontage_unit', sa.String(length=20), nullable=True),
    sa.Column('title_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['active_geometry_id'], ['geometry_versions.id'], name='fk_property_active_geometry', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['geo_units.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['geo_units.id'], ),
    sa.ForeignKeyConstraint(['tehsil_id'], ['geo_units.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['geo_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_area_sqm_derived'), 'properties', ['area_sqm_derived'], unique=False)
    op.create_index(op.f('ix_properties_code'), 'properties', ['code'], unique=False)
    op.create_index(op.f('ix_properties_district_id'), 'properties', ['district_id'], unique=False)
    op.create_index(op.f('ix_properties_khasra_number'), 'properties', ['khasra_number'], unique=False)
    op.create_index(op.f('ix_properties_land_type'), 'properties', ['land_type'], unique=False)
    op.create_index(op.f('ix_properties_state_id'), 'properties', ['state_id'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_survey_number'), 'properties', ['survey_number'], unique=False)
    op.create_index(op.f('ix_properties_tehsil_id'), 'properties', ['tehsil_id'], unique=False)
    op.create_index(op.f('ix_properties_tenant_id'), 'properties', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_properties_village_id'), 'properties', ['village_id'], unique=False)
    op.create_table('required_document_rules',
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('land_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['document_classes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'scope', 'class_id', name='uq_required_doc_rule')
    )
    op.create_index(op.f('ix_required_document_rules_tenant_id'), 'required_document_rules', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission')
    )
    op.create_table('stage_definitions',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('is_skippable', sa.Boolean(), nullable=False),
    sa.Column('sla_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_template_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'key', name='uq_stage_key')
    )
    op.create_index(op.f('ix_stage_definitions_version_id'), 'stage_definitions', ['version_id'], unique=False)
    op.create_table('tenant_workflow_activations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('land_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('activated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'template_version_id', name='uq_tenant_activation')
    )
    op.create_index(op.f('ix_tenant_workflow_activations_template_version_id'), 'tenant_workflow_activations', ['template_version_id'], unique=False)
    op.create_index(op.f('ix_tenant_workflow_activations_tenant_id'), 'tenant_workflow_activations', ['tenant_id'], unique=False)
    op.create_table('checklist_item_definitions',
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('document_class_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'key', name='uq_checklist_key')
    )
    op.create_index(op.f('ix_checklist_item_definitions_stage_id'), 'checklist_item_definitions', ['stage_id'], unique=False)
    op.create_table('deals',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('activation_id', sa.Uuid(), nullable=True),
    sa.Column('current_stage_id', sa.Uuid(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_override_reason', sa.Text(), nullable=True),
    sa.Column('active_override_by_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('negotiated_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('next_action', sa.String(length=500), nullable=True),
    sa.Column('next_action_due', sa.Date(), nullable=True),
    sa.Column('next_action_assignee_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['activation_id'], ['tenant_workflow_activations.id'], ),
    sa.ForeignKeyConstraint(['active_override_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['stage_definitions.id'], ),
    sa.ForeignKeyConstraint(['next_action_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['workflow_template_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_code'), 'deals', ['code'], unique=False)
    op.create_index(op.f('ix_deals_current_stage_id'), 'deals', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_deals_is_active'), 'deals', ['is_active'], unique=False)
    op.create_index(op.f('ix_deals_next_action_assignee_id'), 'deals', ['next_action_assignee_id'], unique=False)
    op.create_index(op.f('ix_deals_property_id'), 'deals', ['property_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_index(op.f('ix_deals_tenant_id'), 'deals', ['tenant_id'], unique=False)
    op.create_table('nearby_features',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('ref', sa.String(length=60), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nearby_features_property_id'), 'nearby_features', ['property_id'], unique=False)
    op.create_index(op.f('ix_nearby_features_tenant_id'), 'nearby_features', ['tenant_id'], unique=False)
    op.create_table('property_assignments',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'user_id', name='uq_property_assignment')
    )
    op.create_index(op.f('ix_property_assignments_property_id'), 'property_assignments', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_assignments_user_id'), 'property_assignments', ['user_id'], unique=False)
    op.create_table('property_owners',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('ownership_type', sa.String(length=20), nullable=False),
    sa.Column('share_percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('record_reference', sa.String(length=300), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('ended_reason', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name='fk_property_owner_source_doc', use_alter=True),
    sa.ForeignKeyConstraint(['supersedes_id'], ['property_owners.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_owners_is_current'), 'property_owners', ['is_current'], unique=False)
    op.create_index(op.f('ix_property_owners_owner_id'), 'property_owners', ['owner_id'], unique=False)
    op.create_index(op.f('ix_property_owners_property_id'), 'property_owners', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_owners_tenant_id'), 'property_owners', ['tenant_id'], unique=False)
    op.create_table('agreements',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('signed_on', sa.Date(), nullable=True),
    sa.Column('registered_on', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('key_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_agreement_document', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_deal_id'), 'agreements', ['deal_id'], unique=False)
    op.create_index(op.f('ix_agreements_tenant_id'), 'agreements', ['tenant_id'], unique=False)
    op.create_table('deal_assignments',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'user_id', name='uq_deal_assignment')
    )
    op.create_index(op.f('ix_deal_assignments_deal_id'), 'deal_assignments', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_assignments_user_id'), 'deal_assignments', ['user_id'], unique=False)
    op.create_table('deal_ownership_snapshots',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('owners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('taken_by_id', sa.Uuid(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_ownership_snapshots_deal_id'), 'deal_ownership_snapshots', ['deal_id'], unique=False)
    op.create_table('deal_scores',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['scoring_models.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_scores_computed_at'), 'deal_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_deal_scores_deal_id'), 'deal_scores', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_scores_tenant_id'), 'deal_scores', ['tenant_id'], unique=False)
    op.create_table('deal_stage_transitions',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage_id', sa.Uuid(), nullable=True),
    sa.Column('to_stage_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('bypassed_stage_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('bypassed_checklist_item_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['stage_definitions.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['stage_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_stage_transitions_deal_id'), 'deal_stage_transitions', ['deal_id'], unique=False)
    op.create_table('deal_stages',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('stage_definition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bypassed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bypassed_by_id', sa.Uuid(), nullable=True),
    sa.Column('bypass_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bypassed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_definition_id'], ['stage_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'stage_definition_id', name='uq_deal_stage')
    )
    op.create_index(op.f('ix_deal_stages_deal_id'), 'deal_stages', ['deal_id'], unique=False)
    op.create_table('due_diligence_items',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_due_diligence_items_assignee_id'), 'due_diligence_items', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_due_diligence_items_category'), 'due_diligence_items', ['category'], unique=False)
    op.create_index(op.f('ix_due_diligence_items_deal_id'), 'due_diligence_items', ['deal_id'], unique=False)
    op.create_index(op.f('ix_due_diligence_items_tenant_id'), 'due_diligence_items', ['tenant_id'], unique=False)
    op.create_table('negotiation_entries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_entries_deal_id'), 'negotiation_entries', ['deal_id'], unique=False)
    op.create_index(op.f('ix_negotiation_entries_tenant_id'), 'negotiation_entries', ['tenant_id'], unique=False)
    op.create_table('payment_milestones',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('payee_owner_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['payee_owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_milestones_deal_id'), 'payment_milestones', ['deal_id'], unique=False)
    op.create_index(op.f('ix_payment_milestones_due_date'), 'payment_milestones', ['due_date'], unique=False)
    op.create_index(op.f('ix_payment_milestones_status'), 'payment_milestones', ['status'], unique=False)
    op.create_index(op.f('ix_payment_milestones_tenant_id'), 'payment_milestones', ['tenant_id'], unique=False)
    op.create_table('site_visits',
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('meeting_point', sa.String(length=500), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_lat', sa.Float(), nullable=True),
    sa.Column('check_in_lng', sa.Float(), nullable=True),
    sa.Column('check_in_accuracy_m', sa.Float(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_lat', sa.Float(), nullable=True),
    sa.Column('check_out_lng', sa.Float(), nullable=True),
    sa.Column('track', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('calendar_provider', sa.String(length=30), nullable=True),
    sa.Column('calendar_external_ref', sa.String(length=300), nullable=True),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_ref', name='uq_site_visit_client_ref')
    )
    op.create_index(op.f('ix_site_visits_deal_id'), 'site_visits', ['deal_id'], unique=False)
    op.create_index(op.f('ix_site_visits_property_id'), 'site_visits', ['property_id'], unique=False)
    op.create_index(op.f('ix_site_visits_scheduled_start'), 'site_visits', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_site_visits_status'), 'site_visits', ['status'], unique=False)
    op.create_index(op.f('ix_site_visits_tenant_id'), 'site_visits', ['tenant_id'], unique=False)
    op.create_table('deal_checklist_items',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('deal_stage_id', sa.Uuid(), nullable=False),
    sa.Column('item_definition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('completed_by_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_stage_id'], ['deal_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_checklist_document', use_alter=True),
    sa.ForeignKeyConstraint(['item_definition_id'], ['checklist_item_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_checklist_items_deal_id'), 'deal_checklist_items', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_checklist_items_deal_stage_id'), 'deal_checklist_items', ['deal_stage_id'], unique=False)
    op.create_table('documents',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('site_visit_id', sa.Uuid(), nullable=True),
    sa.Column('access_policy', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('renewal_due_date', sa.Date(), nullable=True),
    sa.Column('reference_number', sa.String(length=200), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['document_classes.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_visit_id'], ['site_visits.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_class_id'), 'documents', ['class_id'], unique=False)
    op.create_index(op.f('ix_documents_deal_id'), 'documents', ['deal_id'], unique=False)
    op.create_index(op.f('ix_documents_expiry_date'), 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_property_id'), 'documents', ['property_id'], unique=False)
    op.create_index(op.f('ix_documents_review_status'), 'documents', ['review_status'], unique=False)
    op.create_index(op.f('ix_documents_site_visit_id'), 'documents', ['site_visit_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('site_visit_attendees',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['site_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_visit_attendees_user_id'), 'site_visit_attendees', ['user_id'], unique=False)
    op.create_index(op.f('ix_site_visit_attendees_visit_id'), 'site_visit_attendees', ['visit_id'], unique=False)
    op.create_table('site_visit_media',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=600), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['site_visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'client_ref', name='uq_visit_media_client_ref')
    )
    op.create_index(op.f('ix_site_visit_media_tenant_id'), 'site_visit_media', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_site_visit_media_visit_id'), 'site_visit_media', ['visit_id'], unique=False)
    op.create_table('site_visit_notes',
    sa.Column('visit_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['site_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'client_ref', name='uq_visit_note_client_ref')
    )
    op.create_index(op.f('ix_site_visit_notes_visit_id'), 'site_visit_notes', ['visit_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('deal_stage_id', sa.Uuid(), nullable=True),
    sa.Column('site_visit_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Uuid(), nullable=True),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['deal_stage_id'], ['deal_stages.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['site_visit_id'], ['site_visits.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_client_ref'), 'tasks', ['client_ref'], unique=False)
    op.create_index(op.f('ix_tasks_deal_id'), 'tasks', ['deal_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_property_id'), 'tasks', ['property_id'], unique=False)
    op.create_index(op.f('ix_tasks_site_visit_id'), 'tasks', ['site_visit_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('document_access_grants',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_document_grant')
    )
    op.create_index(op.f('ix_document_access_grants_document_id'), 'document_access_grants', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_grants_user_id'), 'document_access_grants', ['user_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=600), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_no', name='uq_document_version')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_sha256'), 'document_versions', ['sha256'], unique=False)
    op.create_table('map_uploads',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('file_kind', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=600), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_uploads_deal_id'), 'map_uploads', ['deal_id'], unique=False)
    op.create_index(op.f('ix_map_uploads_property_id'), 'map_uploads', ['property_id'], unique=False)
    op.create_index(op.f('ix_map_uploads_sha256'), 'map_uploads', ['sha256'], unique=False)
    op.create_index(op.f('ix_map_uploads_tenant_id'), 'map_uploads', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('payee_owner_id', sa.Uuid(), nullable=True),
    sa.Column('receipt_document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['payment_milestones.id'], ),
    sa.ForeignKeyConstraint(['payee_owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_deal_id'), 'payments', ['deal_id'], unique=False)
    op.create_index(op.f('ix_payments_milestone_id'), 'payments', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('document_reviews',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_reviews_document_id'), 'document_reviews', ['document_id'], unique=False)
    op.create_table('geometry_versions',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('geojson', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_upload_id', sa.Uuid(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('georeference', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('perimeter_m', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('calc_method', sa.String(length=60), nullable=True),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_upload_id'], ['map_uploads.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['geometry_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'version_no', name='uq_geometry_version')
    )
    op.create_index(op.f('ix_geometry_versions_property_id'), 'geometry_versions', ['property_id'], unique=False)
    op.create_index(op.f('ix_geometry_versions_source_upload_id'), 'geometry_versions', ['source_upload_id'], unique=False)
    op.create_index(op.f('ix_geometry_versions_status'), 'geometry_versions', ['status'], unique=False)
    op.create_index(op.f('ix_geometry_versions_tenant_id'), 'geometry_versions', ['tenant_id'], unique=False)
    op.create_table('map_processing_runs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('background_job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extracted_geometry_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['background_job_id'], ['background_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['map_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_processing_runs_tenant_id'), 'map_processing_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_map_processing_runs_upload_id'), 'map_processing_runs', ['upload_id'], unique=False)
    op.create_table('site_records',
    sa.Column('site_code', sa.String(length=20), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('approval_state', sa.String(length=20), nullable=False),
    sa.Column('active_revision_id', sa.Uuid(), nullable=True),
    sa.Column('pending_revision_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_map_upload_id', sa.Uuid(), nullable=True),
    sa.Column('plot_label', sa.String(length=100), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('village_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('area_unit', sa.String(length=20), nullable=True),
    sa.Column('area_sqm_derived', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('length_m_derived', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('width_m_derived', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('usage_type', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['active_revision_id'], ['site_record_revisions.id'], name='fk_site_active_revision', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['geo_units.id'], ),
    sa.ForeignKeyConstraint(['pending_revision_id'], ['site_record_revisions.id'], name='fk_site_pending_revision', use_alter=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_map_upload_id'], ['map_uploads.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['geo_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'site_code', name='uq_site_code')
    )
    op.create_index(op.f('ix_site_records_approval_state'), 'site_records', ['approval_state'], unique=False)
    op.create_index(op.f('ix_site_records_area_sqm_derived'), 'site_records', ['area_sqm_derived'], unique=False)
    op.create_index(op.f('ix_site_records_district_id'), 'site_records', ['district_id'], unique=False)
    op.create_index(op.f('ix_site_records_plot_label'), 'site_records', ['plot_label'], unique=False)
    op.create_index(op.f('ix_site_records_property_id'), 'site_records', ['property_id'], unique=False)
    op.create_index(op.f('ix_site_records_property_type'), 'site_records', ['property_type'], unique=False)
    op.create_index(op.f('ix_site_records_source_document_id'), 'site_records', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_site_records_source_map_upload_id'), 'site_records', ['source_map_upload_id'], unique=False)
    op.create_index(op.f('ix_site_records_status'), 'site_records', ['status'], unique=False)
    op.create_index(op.f('ix_site_records_tenant_id'), 'site_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_site_records_unit_number'), 'site_records', ['unit_number'], unique=False)
    op.create_index(op.f('ix_site_records_village_id'), 'site_records', ['village_id'], unique=False)
    op.create_table('site_record_revisions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_record_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('derived', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('match_decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_record_id'], ['site_records.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_record_id', 'revision_no', name='uq_site_revision')
    )
    op.create_index(op.f('ix_site_record_revisions_site_record_id'), 'site_record_revisions', ['site_record_id'], unique=False)
    op.create_index(op.f('ix_site_record_revisions_status'), 'site_record_revisions', ['status'], unique=False)
    op.create_index(op.f('ix_site_record_revisions_tenant_id'), 'site_record_revisions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_record_revisions_tenant_id'), table_name='site_record_revisions')
    op.drop_index(op.f('ix_site_record_revisions_status'), table_name='site_record_revisions')
    op.drop_index(op.f('ix_site_record_revisions_site_record_id'), table_name='site_record_revisions')
    op.drop_table('site_record_revisions')
    op.drop_index(op.f('ix_site_records_village_id'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_unit_number'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_tenant_id'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_status'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_source_map_upload_id'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_source_document_id'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_property_type'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_property_id'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_plot_label'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_district_id'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_area_sqm_derived'), table_name='site_records')
    op.drop_index(op.f('ix_site_records_approval_state'), table_name='site_records')
    op.drop_table('site_records')
    op.drop_index(op.f('ix_map_processing_runs_upload_id'), table_name='map_processing_runs')
    op.drop_index(op.f('ix_map_processing_runs_tenant_id'), table_name='map_processing_runs')
    op.drop_table('map_processing_runs')
    op.drop_index(op.f('ix_geometry_versions_tenant_id'), table_name='geometry_versions')
    op.drop_index(op.f('ix_geometry_versions_status'), table_name='geometry_versions')
    op.drop_index(op.f('ix_geometry_versions_source_upload_id'), table_name='geometry_versions')
    op.drop_index(op.f('ix_geometry_versions_property_id'), table_name='geometry_versions')
    op.drop_table('geometry_versions')
    op.drop_index(op.f('ix_document_reviews_document_id'), table_name='document_reviews')
    op.drop_table('document_reviews')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_milestone_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_deal_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_map_uploads_tenant_id'), table_name='map_uploads')
    op.drop_index(op.f('ix_map_uploads_sha256'), table_name='map_uploads')
    op.drop_index(op.f('ix_map_uploads_property_id'), table_name='map_uploads')
    op.drop_index(op.f('ix_map_uploads_deal_id'), table_name='map_uploads')
    op.drop_table('map_uploads')
    op.drop_index(op.f('ix_document_versions_sha256'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_access_grants_user_id'), table_name='document_access_grants')
    op.drop_index(op.f('ix_document_access_grants_document_id'), table_name='document_access_grants')
    op.drop_table('document_access_grants')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_site_visit_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_property_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deal_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_client_ref'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_site_visit_notes_visit_id'), table_name='site_visit_notes')
    op.drop_table('site_visit_notes')
    op.drop_index(op.f('ix_site_visit_media_visit_id'), table_name='site_visit_media')
    op.drop_index(op.f('ix_site_visit_media_tenant_id'), table_name='site_visit_media')
    op.drop_table('site_visit_media')
    op.drop_index(op.f('ix_site_visit_attendees_visit_id'), table_name='site_visit_attendees')
    op.drop_index(op.f('ix_site_visit_attendees_user_id'), table_name='site_visit_attendees')
    op.drop_table('site_visit_attendees')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_site_visit_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_review_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_property_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_expiry_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_deal_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_class_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_deal_checklist_items_deal_stage_id'), table_name='deal_checklist_items')
    op.drop_index(op.f('ix_deal_checklist_items_deal_id'), table_name='deal_checklist_items')
    op.drop_table('deal_checklist_items')
    op.drop_index(op.f('ix_site_visits_tenant_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_status'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_scheduled_start'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_property_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_deal_id'), table_name='site_visits')
    op.drop_table('site_visits')
    op.drop_index(op.f('ix_payment_milestones_tenant_id'), table_name='payment_milestones')
    op.drop_index(op.f('ix_payment_milestones_status'), table_name='payment_milestones')
    op.drop_index(op.f('ix_payment_milestones_due_date'), table_name='payment_milestones')
    op.drop_index(op.f('ix_payment_milestones_deal_id'), table_name='payment_milestones')
    op.drop_table('payment_milestones')
    op.drop_index(op.f('ix_negotiation_entries_tenant_id'), table_name='negotiation_entries')
    op.drop_index(op.f('ix_negotiation_entries_deal_id'), table_name='negotiation_entries')
    op.drop_table('negotiation_entries')
    op.drop_index(op.f('ix_due_diligence_items_tenant_id'), table_name='due_diligence_items')
    op.drop_index(op.f('ix_due_diligence_items_deal_id'), table_name='due_diligence_items')
    op.drop_index(op.f('ix_due_diligence_items_category'), table_name='due_diligence_items')
    op.drop_index(op.f('ix_due_diligence_items_assignee_id'), table_name='due_diligence_items')
    op.drop_table('due_diligence_items')
    op.drop_index(op.f('ix_deal_stages_deal_id'), table_name='deal_stages')
    op.drop_table('deal_stages')
    op.drop_index(op.f('ix_deal_stage_transitions_deal_id'), table_name='deal_stage_transitions')
    op.drop_table('deal_stage_transitions')
    op.drop_index(op.f('ix_deal_scores_tenant_id'), table_name='deal_scores')
    op.drop_index(op.f('ix_deal_scores_deal_id'), table_name='deal_scores')
    op.drop_index(op.f('ix_deal_scores_computed_at'), table_name='deal_scores')
    op.drop_table('deal_scores')
    op.drop_index(op.f('ix_deal_ownership_snapshots_deal_id'), table_name='deal_ownership_snapshots')
    op.drop_table('deal_ownership_snapshots')
    op.drop_index(op.f('ix_deal_assignments_user_id'), table_name='deal_assignments')
    op.drop_index(op.f('ix_deal_assignments_deal_id'), table_name='deal_assignments')
    op.drop_table('deal_assignments')
    op.drop_index(op.f('ix_agreements_tenant_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_deal_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_property_owners_tenant_id'), table_name='property_owners')
    op.drop_index(op.f('ix_property_owners_property_id'), table_name='property_owners')
    op.drop_index(op.f('ix_property_owners_owner_id'), table_name='property_owners')
    op.drop_index(op.f('ix_property_owners_is_current'), table_name='property_owners')
    op.drop_table('property_owners')
    op.drop_index(op.f('ix_property_assignments_user_id'), table_name='property_assignments')
    op.drop_index(op.f('ix_property_assignments_property_id'), table_name='property_assignments')
    op.drop_table('property_assignments')
    op.drop_index(op.f('ix_nearby_features_tenant_id'), table_name='nearby_features')
    op.drop_index(op.f('ix_nearby_features_property_id'), table_name='nearby_features')
    op.drop_table('nearby_features')
    op.drop_index(op.f('ix_deals_tenant_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_property_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_next_action_assignee_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_is_active'), table_name='deals')
    op.drop_index(op.f('ix_deals_current_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_code'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_checklist_item_definitions_stage_id'), table_name='checklist_item_definitions')
    op.drop_table('checklist_item_definitions')
    op.drop_index(op.f('ix_tenant_workflow_activations_tenant_id'), table_name='tenant_workflow_activations')
    op.drop_index(op.f('ix_tenant_workflow_activations_template_version_id'), table_name='tenant_workflow_activations')
    op.drop_table('tenant_workflow_activations')
    op.drop_index(op.f('ix_stage_definitions_version_id'), table_name='stage_definitions')
    op.drop_table('stage_definitions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_required_document_rules_tenant_id'), table_name='required_document_rules')
    op.drop_table('required_document_rules')
    op.drop_index(op.f('ix_properties_village_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_tenant_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_tehsil_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_survey_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_state_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_land_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_khasra_number'), table_name='properties')
    op.drop_index(op.f('ix_properties_district_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_area_sqm_derived'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_owner_contacts_owner_id'), table_name='owner_contacts')
    op.drop_table('owner_contacts')
    op.drop_table('membership_roles')
    op.drop_index(op.f('ix_workflow_template_versions_template_id'), table_name='workflow_template_versions')
    op.drop_table('workflow_template_versions')
    op.drop_index(op.f('ix_web_sessions_user_id'), table_name='web_sessions')
    op.drop_table('web_sessions')
    op.drop_table('tenant_template_permissions')
    op.drop_table('tenant_sequences')
    op.drop_index(op.f('ix_tenant_memberships_user_id'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_tenant_invitations_tenant_id'), table_name='tenant_invitations')
    op.drop_table('tenant_invitations')
    op.drop_index(op.f('ix_scoring_models_tenant_id'), table_name='scoring_models')
    op.drop_table('scoring_models')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_owners_verification_status'), table_name='owners')
    op.drop_index(op.f('ix_owners_tenant_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_full_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_code'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_geo_units_tenant_id'), table_name='geo_units')
    op.drop_index(op.f('ix_geo_units_parent_id'), table_name='geo_units')
    op.drop_index(op.f('ix_geo_units_level'), table_name='geo_units')
    op.drop_table('geo_units')
    op.drop_index(op.f('ix_document_classes_tenant_id'), table_name='document_classes')
    op.drop_table('document_classes')
    op.drop_index(op.f('ix_device_push_tokens_user_id'), table_name='device_push_tokens')
    op.drop_table('device_push_tokens')
    op.drop_index(op.f('ix_background_jobs_tenant_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_kind'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
